"""impression and bidder table

Revision ID: 20d6f9347176
Revises: 
Create Date: 2023-10-27 18:00:13.461471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d6f9347176'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bidder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bidder_addr'), ['addr'], unique=True)

    op.create_table('impression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impression_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_impression_profile'), ['profile'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impression_profile'))
        batch_op.drop_index(batch_op.f('ix_impression_created_at'))

    op.drop_table('impression')
    with op.batch_alter_table('bidder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bidder_addr'))

    op.drop_table('bidder')
    # ### end Alembic commands ###
