"""add bidnet_id column in impression table

Revision ID: 3f83203165a7
Revises: b1848276eab6
Create Date: 2023-10-28 17:27:09.555165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f83203165a7'
down_revision = 'b1848276eab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bidnet_id', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_impression_bidnet_id'), ['bidnet_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impression_bidnet_id'))
        batch_op.drop_column('bidnet_id')

    # ### end Alembic commands ###
