"""add impression table

Revision ID: b1848276eab6
Revises: 
Create Date: 2023-10-28 15:23:49.388944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1848276eab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.Column('is_won', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impression_profile'), ['profile'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impression_profile'))

    op.drop_table('impression')
    # ### end Alembic commands ###
